Repository jenkinsci/artifact-manager-s3-plugin, pull requests merged in 2020-01, with the labels that each got.

#105 [JENKINS-59493] Use S3 client to get public URI (follow-up)
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java
Labels: bug

#97 [JENKINS-59493] Use S3 client to get public URI
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
Labels: bug

#106 Updates
  pom.xml
Labels: dependencies

#107 JENKINS-50772: specify content type for uploaded files in S3 (follow-ups)
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
Labels: enhancement

#109 [JENKINS-55017] Allow advanced configuration for other s3 providers (follow-ups)
  README.md
  images/bucket-settings.png
  images/custom-s3-service-configuration.png
  pom.xml
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
  src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/config.jelly
  src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/help-customEndpoint.html
  src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/help-customSigningRegion.html
  src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/help-disableSessionToken.html
  src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/help-useHttp.html
  src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/help-usePathStyleUrl.html
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/ConfigAsCodeTest.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/CustomBehaviorBlobStoreProvider.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/MinioIntegrationTest.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3AbstractTest.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTest.java
  src/test/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/configuration-as-code.yml
Labels: enhancement

#110 [JENKINS-60716] More lenient assertions about Throwable messages
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
Labels: tests
