Repository jenkinsci/artifact-manager-s3-plugin, pull requests merged in 2021-10, with the labels that each got.

#232 enable jdk11 windows builds
  Jenkinsfile
Labels: tests

#238 Replace heavyweight aws-java-sdk with fine-grained plugin
  pom.xml
Labels: enhancement

#239 This entry makes no sense in depmgmt
  pom.xml
Labels: chore
