Repository jenkinsci/artifact-manager-s3-plugin, pull requests merged in 2021-03, with the labels that each got.

#184 fix typo
  README.md
Labels: documentation

#187 [JENKINS-41827] Running MinioIntegrationTest in a more realistic context
  pom.xml
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/MinioIntegrationTest.java
Labels: tests

#188 Upgrade Guava to latest release
  .github/dependabot.yml
  pom.xml
Labels: dependencies

#196 RealJenkinsRule updated, passing -Xmx100m
  pom.xml
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/MinioIntegrationTest.java
Labels: tests
