Repository jenkinsci/artifact-manager-s3-plugin, pull requests merged in 2021-04, with the labels that each got.

#199 Typo in README
  README.md
Labels: documentation

#204 doValidateS3BucketConfig could throw AssertionError
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
Labels: bug

#203 Update POM
  pom.xml
Labels: chore
