Repository jenkinsci/artifact-manager-s3-plugin, pull requests merged in 2023-01, with the labels that each got.

#339 Increasing Spotbugs level and fixing Spotbugs issues
  pom.xml
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStore.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTest.java
Labels: chore

#350 Skip test if using `AnonymousAWSCredentials`
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3AbstractTest.java
Labels: tests

#349 `JCloudsArtifactManager` fails to archive artifacts when their workspace path is not identical to their archive path
  pom.xml
  src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
  src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
Labels: bug
